typography_spectrum: 0.6343
color:
  brandColors:
    - '#252525'
    - '#808080'
    - '#d1d1d1'
    - '#886111'
    - '#e69d05'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37505
analytics:
  google: null
  facebook: null
  twitter: null
name: Cody Killgore
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Killgore Forge
purpose: []
