name: Killgore Forge
favicon: null
layout_spectrum: 0.1351490227971226
typography_spectrum: 0.7050595916807652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#808080'
    - '#d1d1d1'
    - '#886111'
    - '#e69d05'
  brandStrength: 0.6875
  lightness: 0.14002080680802464
  saturation: 0.6875
  rhythmicContrast: 0.8359727410133928
purpose: []
