name: Cody Killgore
favicon: null
layout_spectrum: 0.59321
typography_spectrum: 0.17434
title: Killgore Forge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9c0b9'
    - '#fefefe'
    - '#160d04'
    - '#6a7476'
    - '#f8f743'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
