name: Cody Killgore
favicon: null
layout_spectrum: 0.1351490227971226
typography_spectrum: 0.44844
title: Killgore Forge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#808080'
    - '#d1d1d1'
    - '#886111'
    - '#e69d05'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
